version: "3.8"

services:
  file-upload-app:
    image: test/ecs-fileuploading:latest
    container_name: file-upload-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AWS_REGION=ap-south-1
    volumes:
      - /data:/app/uploads
    restart: always
